name: Plugin Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version (x.x.x)'
        required: true
        default: 'continuous'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.2

      - name: Install dependencies
        run: dart pub global activate hetu_script_dev_tools

      - name: Check runtime scope resolution
        run: python3 check_scope.py

      - name: Run build
        run: make

      - name: Archive plugin
        run: make archive
        shell: bash

      - name: Verify package contents
        run: make verify

      - name: Upload plugin archive
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/plugin.smplug

      - name: Upload to release (${{ github.event.inputs.version }})
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: build/plugin.smplug
